### ISSUE TITLE
Bug: db2数据库连接 URL 语法无效

### ISSUE THREAD

**Issue by maybe-why-not** [alibaba/ali-dbhub#419]
### Chat2DB Version

v0.0.0 build 20230616055223

### Describe the bug

自己连没问题
![image](https://github.com/alibaba/Chat2DB/assets/29968903/203e7dad-c614-45a1-9341-7405c5328df3)
驱动
https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/jdbc-drivers/Db2/4.26/db2jcc4_4.26.14.jar
连接数据包
![image](https://github.com/alibaba/Chat2DB/assets/29968903/d90999ac-1d54-4bc0-97c3-374541c8e8cc)
报错
```
2023-06-23 18:14:12.512  INFO 3084 --- [o-10821-exec-10] c.a.d.s.w.a.a.BusinessExceptionHandler   : proceed begin:com.alibaba.dbhub.server.web.api.controller.data.source.DataSourceControllerpreConnect ,param:[{"alias":"@localhost","extendInfo":[],"host":"43.*","password":"db2inst1","port":"50000","ssh":{"hostName":"","localPort":"","password":"","port":"","use":false,"userName":""},"type":"DB2","url":"jdbc:db2://43.*:50000","user":"db2inst1"}]
2023-06-23 18:14:12.514 ERROR 3084 --- [o-10821-exec-10] c.a.d.s.domain.support.util.JdbcUtils    : connection fail:

com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10165][10045][4.26.14] 数据库 URL 语法 jdbc:db2://43.*:50000 无效。 ERRORCODE=-4461, SQLSTATE=42815
        at com.ibm.db2.jcc.am.b7.a(b7.java:810)
        at com.ibm.db2.jcc.am.b7.a(b7.java:66)
        at com.ibm.db2.jcc.am.b7.a(b7.java:98)
        at com.ibm.db2.jcc.DB2Driver.tokenizeOptionalPortNumber(DB2Driver.java:881)
        at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:390)
        at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:113)
        at com.alibaba.dbhub.server.domain.support.sql.IDriverManager.getConnection(IDriverManager.java:86)
        at com.alibaba.dbhub.server.domain.support.sql.IDriverManager.getConnection(IDriverManager.java:71)
        at com.alibaba.dbhub.server.domain.support.util.JdbcUtils.testConnect(JdbcUtils.java:165)
        at com.alibaba.dbhub.server.domain.core.impl.DataSourceServiceImpl.preConnect(DataSourceServiceImpl.java:120)
        at com.alibaba.dbhub.server.web.api.controller.data.source.DataSourceController.preConnect(DataSourceController.java:89)
        at com.alibaba.dbhub.server.web.api.controller.data.source.DataSourceController$$FastClassBySpringCGLIB$$cc1af8df.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.alibaba.dbhub.server.web.api.aspect.BusinessExceptionHandler.businessExceptionHandler(BusinessExceptionHandler.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.alibaba.dbhub.server.web.api.aspect.ConnectionInfoHandler.connectionInfoHandler(ConnectionInfoHandler.java:56)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at com.alibaba.dbhub.server.web.api.controller.data.source.DataSourceController$$EnhancerBySpringCGLIB$$915d1081.preConnect(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.dbhub.server.start.config.interceptor.CorsFilter.doFilter(CorsFilter.java:38)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.NoSuchElementException: null
        at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:347)
        at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:375)
        at com.ibm.db2.jcc.DB2Driver.tokenizeOptionalPortNumber(DB2Driver.java:860)
        ... 92 common frames omitted

2023-06-23 18:14:12.564  INFO 3084 --- [o-10821-exec-10] c.a.d.s.w.a.a.BusinessExceptionHandler   : proceed end:com.alibaba.dbhub.server.web.api.controller.data.source.DataSourceControllerpreConnect, result:{"success":false}, cost:52

```

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
